project:
  type: website

website:
  title: "rOpenSci Dashboard"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - editors.qmd
      - ed-reviews.qmd
      - reviews.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
